name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      has-releases: ${{ steps.create-release.outputs.has-releases }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install Rust
        run: |
          rustup install nightly-2023-08-18 --no-self-update
          rustup default nightly-2023-08-18

      - name: Install cargo-dist
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/axodotdev/cargo-dist/releases/download/v0.0.7/cargo-dist-installer.sh | sh

      - name: Create Release
        id: create-release
        run: |
          cargo dist plan --tag=${{ github.ref_name }} --output-format=json > dist-manifest.json

          ANNOUNCEMENT_TITLE=$(jq --raw-output ".announcement_title" dist-manifest.json)
          IS_PRERELEASE=$(jq --raw-output ".announcement_is_prerelease" dist-manifest.json)

          jq --raw-output ".announcement_github_body" dist-manifest.json > new_dist_announcement.md
          gh release create ${{ github.ref_name }} --draft --prerelease="$IS_PRERELEASE" --title="$ANNOUNCEMENT_TITLE" --notes-file=new_dist_announcement.md

          gh release upload ${{ github.ref_name }} dist-manifest.json

          HAS_RELEASES=$(jq --raw-output ".releases != null" dist-manifest.json)
          echo "has-releases=$HAS_RELEASES" >> "$GITHUB_OUTPUT"

  upload-artifacts:
    needs: create-release
    if: ${{ needs.create-release.outputs.has-releases == 'true' }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            dist-args: --artifacts=local --target=x86_64-unknown-linux-gnu
            install-dist: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/axodotdev/cargo-dist/releases/download/v0.0.7/cargo-dist-installer.sh | sh
          - os: windows-2022
            dist-args: --artifacts=local --target=x86_64-pc-windows-msvc
            install-dist: irm  https://github.com/axodotdev/cargo-dist/releases/download/v0.0.7/cargo-dist-installer.ps1 | iex

    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install Rust
        run: |
          rustup install nightly-2023-08-18 --no-self-update
          rustup default nightly-2023-08-18

      - name: Add x86_64-pc-windows-gnu target
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: rustup target add x86_64-pc-windows-gnu

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2.7.7

      - name: Install cargo-dist
        run: ${{ matrix.install-dist }}

      - name: Install packages (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install gcc-mingw-w64 libgtk-3-dev

      - name: Install packages (MacOS)
        if: runner.os == 'macOS'
        run: |
          NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install mingw-w64

      - name: Run cargo-dist
        run: |
          cargo dist build --tag=${{ github.ref_name }} --output-format=json ${{ matrix.dist-args }} > dist-manifest.json

          jq --raw-output ".artifacts[]?.path | select( . != null )" dist-manifest.json > uploads.txt
          gh release upload ${{ github.ref_name }} $(cat uploads.txt)
